CREATE DATABASE IF NOT EXISTS lab;
CREATE USER IF NOT EXISTS 'lab'@'%' IDENTIFIED BY 'labpass';
GRANT ALL PRIVILEGES ON lab.* TO 'lab'@'%';
GRANT REPLICATION CLIENT, PROCESS, SELECT ON *.* TO 'lab'@'%';
FLUSH PRIVILEGES;
